# This file is part of the ftschindler-work/gamm-2019-talk-on-conservative-rb project:
#   https://github.com/ftschindler-work/gamm-2019-talk-on-conservative-rb
# The copyright lies with the authors of this file (see below).
# License: BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)

[ -z "$PS1" ] && return

export HISTSIZE=10000
export HISTFILESIZE=${HISTSIZE}
export HISTCONTROL=ignoreboth
shopt -s cdspell
shopt -s histappend
shopt -s checkwinsize
shopt -s cmdhist
shopt -s dotglob
shopt -s expand_aliases
shopt -s extglob
shopt -s hostcomplete
shopt -s nocaseglob

set show-all-if-ambiguous on
set show-all-if-unmodified on

alias ls='ls --time-style=+"%d.%m.%Y %H:%M" --color=auto'
alias ll='ls -hl  --time-style=+"%d.%m.%Y %H:%M" --color=auto'
alias la='ls -lah --time-style=+"%d.%m.%Y %H:%M" --color=auto'
alias grep='grep -n'
alias psa='ps -Af | \grep -v grep | \grep'

export LANG=en_US.UTF-8
export QT_QPA_PLATFORMTHEME="qt5ct"

source /data/dune/venv/gamm-2019-talk-on-conservative-rb/bin/activate
cd /data/home/gamm-2019-talk-on-conservative-rb

