cd $HOME
source .bashrc

echo "This is a container based on debian stable"
echo "the current user is apt capable."
echo ""
echo "To reproduce the results, go to"
echo ""
echo "  /data/home/gamm-2019-talk-on-conservative-rb/dune-gdt/examples"
echo ""
echo "and execute"
echo ""
echo "  python ./gamm-2019-talk-on-conservative-rb-OS2015-multiscale-example.py"

